version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-yogasimha-mlops(project)}"
    image: cybulde-template
    platform: linux/amd64
    container_name: cybulde-template-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-kyuksel}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-kyuksel}/.config/gcloud
    ports:
      - 8080:8080
    ipc: host
    init: true

